export const TemperamentosMestizos = [
    { nombre: 'Afectuosos', descripcion: 'Cariñosos y afectuosos, siendo excelentes compañeros para familias, personas solteras y personas mayores.' },
    { nombre: 'Juguetones', descripcion: 'Tienen una naturaleza juguetona, pero también disfrutan de largas siestas.' },
    { nombre: 'Tercos', descripcion: 'Pueden ser tercos a veces, lo que requiere una capacitación paciente y constante.' },
    { nombre: 'Inteligentes', descripcion: 'Inteligente o extremadamente inteligente.' },
    { nombre: 'Ágiles', descripcion: 'Capacidad de moverse rápida y fácilmente excepcionales en actividades de trabajo y deportes caninos como el agility.' },
    { nombre: 'Leales', descripcion: 'Son leales con sus familias.' },
    { nombre: 'Reservados', descripcion: 'Reservados con extraños.' },
    { nombre: 'Protectores', descripcion: 'Tienen un fuerte instinto de protección hacia su familia.' },
    { nombre: 'Versátiles', descripcion: 'Son perros muy versátiles que se desempeñan bien en una variedad de roles.' },
    { nombre: 'Amigables', descripcion: 'Conocidos por ser perros amigables.' },
    { nombre: 'Gentil', descripcion: 'Tienen una disposición suave y gentil, lo que los hace excelentes compañeros para familias.' },
    { nombre: 'Sociables', descripcion: 'Perros muy sociables que disfrutan de la compañía de personas y otros animales.' },
    { nombre: 'Valientes', descripcion: 'Perros valientes, alertas y leales, con una actitud vivaz y enérgica.' },
    { nombre: 'Tranquilos', descripcion: 'Disposición tranquila y calmada, lo que los convierte en excelentes compañeros para familias y personas mayores.' },
    { nombre: 'Extrovertido', descripcion: 'Naturaleza extrovertida y sociable, disfrutan de la compañía humana y pueden llevarse bien con otros animales.' },
    { nombre: 'Curiosos', descripcion: 'Inclinado a aprender lo que no conoce.' },
    { nombre: 'Independientes', descripcion: 'Naturaleza independiente, que no tiene dependencia, que no depende de otro.' },
    { nombre: 'Calmados', descripcion: 'Tienen una naturaleza calmada y digna.' },
    { nombre: 'Adaptables', descripcion: 'Se adapta a diferentes entornos. Pueden vivir bien en apartamentos.' },
    { nombre: 'Compatibilidad', descripcion: 'Son excelentes compañeros para familias. También son adecuados para personas mayores.' },
    { nombre: 'Dulce', descripcion: 'Es especialmente tierno con los niños y puede ser un excelente compañero familiar.' },
    { nombre: 'Alerta', descripcion: 'Es un perro alerta que alerta de la presencia de extraños, lo que lo convierte en un buen guardián.' },
    { nombre: 'Dócil', descripcion: 'Suave, apacible, que recibe fácilmente la enseñanza. Es generalmente dócil y cariñoso con su familia.' },
    { nombre: 'Trabajador', descripcion: 'Tiene un fuerte instinto de trabajo y disfruta realizar tareas, ya sea pastoreo o actividades recreativas como agility.' },
    { nombre: 'Cauteloso', descripcion: 'Puede ser un poco reservado con extraños, pero no es agresivo.' },
    { nombre: 'Vocal', descripcion: 'Se comunica con aullidos/maullidos, lo que refleja su herencia ártica.' },
    { nombre: 'Inquisitivos', descripcion: 'Conocido por su naturaleza activa, curiosa e inquisitiva.' },
    { nombre: 'Apegados', descripcion: 'Muy apegados a sus dueños y pueden sufrir ansiedad por separación si se les deja solos por mucho tiempo.' },
    { nombre: 'Tolerantes', descripcion: 'Tienen una actitud tolerante y paciente.' },
    { nombre: 'No muy Vocales', descripcion: 'No son vocales y suelen maullar/ladrar de manera suave cuando lo hacen.' },
    { nombre: 'Vocalización Moderada', descripcion: 'No son excesivamente vocales, pero comunicarán sus necesidades de manera clara y concisa.' },
    { nombre: 'Silencioso', descripcion: 'No suelen ser ruidosos.' },
    { nombre: 'Cazadores', descripcion: 'Con un instinto cazador muy desarrollado, lo que los hace hábiles cazadores de aves, ratones y otros roedores.' },
    { nombre: 'Personalidad "Gato-Perro"', descripcion: 'A menudo sigue a las personas por la casa como lo haría un perro. Disfrutan de la atención constante y de estar en contacto con sus humanos.' },
    { nombre: 'Comunicativos', descripcion: 'Muy vocales que no dudan en expresar sus necesidades y deseos a través de maullidos y otros sonidos.' },
    { nombre: 'No muy activos', descripcion: 'No son tan juguetones como algunas otras razas, prefiriendo pasar su tiempo descansando y observando su entorno.' }
];
